apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-bundle-overriding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-bundle-overriding
    app.kubernetes.io/part-of: test-app-wugd
  name: build-suite-test-bundle-overriding
  namespace: build-e2e-xpqz-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-suite-test-bundle-overriding
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-suite-test-bundle-overriding
    spec:
      containers:
      - image: quay.io/psturc/test-images:a38a476e2ba34ec692f9dca679d08b83
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
